apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMAuditConfig
metadata:
  name: iamauditconfig-storage
  namespace: abcd
spec:
  service: StorageBucket
  auditLogConfigs:
    - logType: DATA_WRITE
    - logType: DATA_READ
  resourceRef:
    kind: Project
    name: "kcc-master"
