apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMAuditConfig
metadata:
  name: iamauditconfig-storage5
  namespace: abcd
spec:
  service: storage.googleapis.com
  auditLogConfigs:
    - logType: DATA_WRITE
    - logType: DATA_READ
  resourceRef:
    kind: Project
