apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: gke-anthos-storages
  namespace: abcd
spec:
  versioning:
    enabled: true
  uniformBucketLevelAccess: true
  publicAccessPrevention: "enforced"
  encryption:
    kmsKeyRef:
      external: "projects/kcc-master-365107/locations/us/keyRings/test1/cryptoKeys/cmk1" 
  #retentionPolicy:
  #  isLocked: true
  #  retentionPeriod: 3155759000
