apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: gke-anthos-storages
  namespace: abcd
spec:
  versioning:
    enabled: true
  uniformBucketLevelAccess: true
  publicAccessPrevention: "true"
  retentionPolicy:
    isLocked: true
    retentionPeriod: 3155759000
